USE Transportapp;
go

DROP TABLE IF EXISTS PACOTESENTREGADORES;
DROP TABLE IF EXISTS PACOTESSITUACOES;
DROP TABLE IF EXISTS PACOTES;
DROP TABLE IF EXISTS ENTREGADORES;
DROP TABLE IF EXISTS DESTINATARIOS;
DROP TABLE IF EXISTS SITUACOES;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS TRANSPORTADORA;

CREATE TABLE TRANSPORTADORA (
	cnpj BIGINT CONSTRAINT pk_Transport PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	razao_social VARCHAR(100) NOT NULL,
	cep BIGINT NOT NULL,
	telefone VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIOS (
	usuario_id INT CONSTRAINT pk_usuario PRIMARY KEY NOT NULL,
	cpf BIGINT NOT NULL UNIQUE,
	senha VARCHAR(100) NOT NULL,
	admin_Us TINYINT NOT NULL,
);

CREATE TABLE SITUACOES (
	situacao_id INT CONSTRAINT pk_situacoes PRIMARY KEY NOT NULL,
	desccricao VARCHAR(10) NOT NULL, 
);

CREATE TABLE DESTINATARIOS (
	destinatario_id INT CONSTRAINT pk_dest PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	cpf BIGINT NOT NULL UNIQUE,
	telefone VARCHAR(25) NOT NULL,
	rua VARCHAR(100) NOT NULL,
	bairro VARCHAR(100) NOT NULL,
	numero INT NOT NULL,
	complemento VARCHAR(50),
	cep BIGINT NOT NULL,
);

CREATE TABLE PACOTES (
	pacote_id INT CONSTRAINT pk_pacotes PRIMARY KEY NOT NULL,
	destinatario_id INT CONSTRAINT fk_dest_id FOREIGN KEY REFERENCES DESTINATARIOS(destinatario_id) NOT NULL,
	numero_pedido INT NOT NULL,
	cpf_recebedor BIGINT,
	foto_pacote BINARY,
);

CREATE TABLE PACOTESSITUACOES (
	pacote_situacao_id INT CONSTRAINT pk_pct_sit PRIMARY KEY NOT NULL,
	pacote_id INT CONSTRAINT fk_pacote_id_SIT FOREIGN KEY REFERENCES PACOTES(pacote_id) NOT NULL,
	situacao_anterior_id INT CONSTRAINT fk_sitAnt_id FOREIGN KEY REFERENCES SITUACOES(situacao_id) NOT NULL,
	situacao_atual_id INT CONSTRAINT fk_sitAtu_id FOREIGN KEY REFERENCES SITUACOES(situacao_id) NOT NULL,
	data_alteracao DATETIME NOT NULL,
);

CREATE TABLE ENTREGADORES (
	entregador_id INT CONSTRAINT pk_entregador PRIMARY KEY NOT NULL,
	usuario_id INT CONSTRAINT fk_usuario_id FOREIGN KEY REFERENCES USUARIOS(usuario_id) NOT NULL,
	cpf BIGINT NOT NULL UNIQUE,
	nome VARCHAR(100) NOT NULL,
	telefone VARCHAR(25) NOT NULL,
	foto_perfil BINARY NOT NULL,
);

CREATE TABLE PACOTESENTREGADORES (
	pacote_entregador_id INT CONSTRAINT pk_pct_entg PRIMARY KEY NOT NULL,
	pacote_id INT CONSTRAINT fk_pacote_id_ENTG FOREIGN KEY REFERENCES PACOTES(pacote_id) NOT NULL,
	entregador_anterior_id INT CONSTRAINT fk_entgAnt_id FOREIGN KEY REFERENCES SITUACOES(situacao_id) NOT NULL,
	entregador_atual_id INT CONSTRAINT fk_entgAtu_id FOREIGN KEY REFERENCES SITUACOES(situacao_id) NOT NULL,
	data_alteracao DATETIME NOT NULL,
);
