/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import entidades.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Geri
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        // com estas linhas o padr�o dos bot�es ser� o do windows
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miParticipantes = new javax.swing.JMenuItem();
        miPalestrantes = new javax.swing.JMenuItem();
        miLocais = new javax.swing.JMenuItem();
        miEventos = new javax.swing.JMenuItem();
        miLerEstatistica = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo de utilização de componentes para ambiente desktop");
        setExtendedState(6);

        jMenu1.setText("Cadastros");

        miParticipantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        miParticipantes.setText("Participantes");
        miParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miParticipantesActionPerformed(evt);
            }
        });
        jMenu1.add(miParticipantes);

        miPalestrantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miPalestrantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tux.png"))); // NOI18N
        miPalestrantes.setText("Palestrantes");
        miPalestrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPalestrantesActionPerformed(evt);
            }
        });
        jMenu1.add(miPalestrantes);

        miLocais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLocais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car.png"))); // NOI18N
        miLocais.setText("Locais");
        miLocais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLocaisActionPerformed(evt);
            }
        });
        jMenu1.add(miLocais);

        miEventos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bricks.png"))); // NOI18N
        miEventos.setText("Eventos");
        miEventos.setToolTipText("Número de cidades feias e modernas");
        miEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEventosActionPerformed(evt);
            }
        });
        jMenu1.add(miEventos);

        miLerEstatistica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLerEstatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/layout_sidebar.png"))); // NOI18N
        miLerEstatistica.setText("Ingressos");
        miLerEstatistica.setToolTipText("Ler dados do arquivo texto");
        miLerEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLerEstatisticaActionPerformed(evt);
            }
        });
        jMenu1.add(miLerEstatistica);
        jMenu1.add(jSeparator1);

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_in.png"))); // NOI18N
        miSair.setText("Sair do Sistema");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        jMenu1.add(miSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Eventos");

        miSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tick.png"))); // NOI18N
        miSobre.setText("Check-in");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        jMenu2.add(miSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miParticipantesActionPerformed
        // TODO add your handling code here:
        JDialog cPart = new CadastroParticipante(this, true);
        cPart.setVisible(true);
    }//GEN-LAST:event_miParticipantesActionPerformed

    private void miPalestrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPalestrantesActionPerformed
        // TODO add your handling code here:
        JDialog cPale = new CadastroPalestrante(this, true);
        cPale.setVisible(true);
    }//GEN-LAST:event_miPalestrantesActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
        // Utilizando a sa�da do sistema com op��es sim e n�o
        Object[] opcoes = {"Sim", "Não"};
        int opc = javax.swing.JOptionPane.showOptionDialog(this,
                "Sair do sistema ?", "Saída do Sistema",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, opcoes, opcoes[0]);
        if (opc == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_miSairActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        // TODO add your handling code here:
//        JDialog sobre = new Sobre(this, true);
//        sobre.setVisible(true);
    }//GEN-LAST:event_miSobreActionPerformed

    private void miLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLocaisActionPerformed
        // TODO add your handling code here:
        JDialog cLocal = new CadastroLocal(this, true);
        cLocal.setVisible(true);
    }//GEN-LAST:event_miLocaisActionPerformed

    private void miEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEventosActionPerformed
        JDialog cEvento = new CadastroEvento(this, true);
        cEvento.setVisible(true);
    }//GEN-LAST:event_miEventosActionPerformed

    private void miLerEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLerEstatisticaActionPerformed
//        try {
//            // TODO add your handling code here:
//            FileReader arq = new FileReader("estcidade.txt");
//            BufferedReader lerArq = new BufferedReader(arq);
//            String aux = "";
//            String linha = lerArq.readLine();
//            while (linha != null) {
//                for (int i = 0; i < linha.length(); i++) {
//                    if (linha.charAt(i) == '|') {
//                        aux += ": ";
//                    } else if (linha.charAt(i) == ';') {
//                        aux += "\n";
//                    } else {
//                        aux += linha.charAt(i);
//                    }
//                }
//                aux += "\n\n";
//                linha = lerArq.readLine();
//            }
//            JOptionPane.showMessageDialog(this, "Dados no arquivo: " + aux);
//            lerArq.close();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Deu erro no arquivo");
//        }
    }//GEN-LAST:event_miLerEstatisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miEventos;
    private javax.swing.JMenuItem miLerEstatistica;
    private javax.swing.JMenuItem miLocais;
    private javax.swing.JMenuItem miPalestrantes;
    private javax.swing.JMenuItem miParticipantes;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSobre;
    // End of variables declaration//GEN-END:variables

}
