--OLIVER LOHANN MAYER 2562502

USE AEROPORTO;

--A)

DROP VIEW IF EXISTS V_VOOS
GO
CREATE VIEW V_VOOS
AS
SELECT 
	AO.NOME AS AEROPORTO_ORIGEM, 
	AD.NOME AS AEROPORTO_DESTINO,
	AD.CIDADE AS CIDADE_DESTINO,
	V.DATAVOO, 
	V.PORTAOEMBARQUE, 
	VCON.DATAVOO AS DATAVOO_CONEXAO, 
	VCON.PORTAOEMBARQUE AS PORTAOEMBARQUE_CONEXAO 
FROM VOO V
	INNER JOIN AEROPORTO AO ON AO.IDAEROPORTO = V.ORIGEM
	INNER JOIN AEROPORTO AD ON AD.IDAEROPORTO = V.DESTINO
	LEFT JOIN VOO VCON ON VCON.IDVOO = V.CONEXAO
WHERE V.DATAVOO BETWEEN '12-04-2023' AND '13-04-2023'
GO
SELECT * FROM V_VOOS

--B)

DROP VIEW IF EXISTS V_PASSAGEIROS_VOOS
GO
CREATE VIEW V_PASSAGEIROS_VOOS
AS
SELECT 
	CONCAT(P.SOBRENOME, ', ',P.NOME) AS PASSAGEIRO,
	V.IDVOO AS NUMERO_VOO,
	V.DATAVOO AS DATA_EMBARQUE,
	V.PORTAOEMBARQUE,
	AO.CIDADE AS CIDADE_ORIGEM, 
	AD.CIDADE AS CIDADE_DESTINO,
	PV.ASSENTO
FROM PASSAGEIRO P
	INNER JOIN PASSAGEIRO_VOO PV ON PV.PASSAGEIRO = P.IDPASSAGEIRO
	INNER JOIN VOO V ON V.IDVOO = PV.VOO
	INNER JOIN AEROPORTO AO ON AO.IDAEROPORTO = V.ORIGEM
	INNER JOIN AEROPORTO AD ON AD.IDAEROPORTO = V.DESTINO
GO
SELECT * FROM V_PASSAGEIROS_VOOS ORDER BY PASSAGEIRO

--C)

DROP VIEW IF EXISTS V_EMBARQUES_DESEMBARQUES_SP
GO
CREATE VIEW V_EMBARQUES_DESEMBARQUES_SP
AS
SELECT 
	P.CPF,
	P.NOME,
	P.SOBRENOME
FROM PASSAGEIRO P
	INNER JOIN PASSAGEIRO_VOO PV ON PV.PASSAGEIRO = P.IDPASSAGEIRO
	INNER JOIN VOO V ON V.IDVOO = PV.VOO
	INNER JOIN AEROPORTO AO ON AO.IDAEROPORTO = V.ORIGEM
	INNER JOIN AEROPORTO AD ON AD.IDAEROPORTO = V.DESTINO
WHERE AO.ESTADO = 'SP' OR AD.ESTADO = 'SP'
GO
SELECT * FROM V_EMBARQUES_DESEMBARQUES_SP